
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    container_name: spring
    build:
      context: ./Этап-3/is-coursework-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      # - DB_HOST=db
      # - DB_NAME=postgres
      # - DB_USER=postgres
      # - DB_PASS=postgres
    depends_on:
      db:
        condition: service_healthy

  front:
    image: is-coursework-front
    build:
      context: ./Этап-4/is-coursework-front
    ports:
      - "3000:3000"
    depends_on:
      - spring
    

